<?php

session_start();

require_once("../config/db.php");
require_once("../functions/functions.php");

if (!isset($_SESSION["user_id"])) {
    header("Location: ../auth/login.php");
    exit();
}

$user = getUserByID($pdo, $_SESSION["user_id"]);

?>

<!DOCTYPE html> 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="../css/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

</head>
<body>
    <div class="layout">
  <aside class="sidebar">
    <div class="logo">
        <img src="../images/placeholder_logo_1.png" alt="PhishAware Logo"> <!-- Replace with non-placeholder logo. Current logo was generated by Gemini for testing. We should probably remove this placeholder before final submission. -->
        <span> | PhishAware</span>
    </div>
    <nav> <!-- Navigation links, map all of these to their respective pages -->
      <a href="admin-dashboard.php"><i class="fas fa-home"></i> | Admin Dashboard</a>
      <a href="training.php"><i class="fas fa-graduation-cap"></i> | Assign Training</a>
      <a href="results.php"><i class="fas fa-chart-line"></i> | User Results</a>
      <a href="user-lookup.php"><i class="fas fa-users"></i> | Users</a>
      <a href="profile.php"><i class="fas fa-user"></i> | My Profile</a>
      <a href="../auth/logout.php"><i class="fas fa-sign-out-alt"></i> | Log Out</a>
    </nav>
  </aside>
  <div class="main">
    <header class="topbar">
    <div class="topbar-left">
        <span>Welcome, <?= htmlspecialchars($user["first_name"]) ?> <?= htmlspecialchars($user["last_name"]) ?></span>

        <div class="search-box">
            <i class="fas fa-search"></i>
            <input type="text" placeholder="Search users, training, reports..."> <!-- Implement a search functionality once available -->
        </div>
    </div>

    <div class="topbar-right">
        <button id="notifications-btn">
            <i class="fas fa-bell"></i>
        </button>

        <div class="profile-menu">
            <i class="fas fa-user" alt="Profile" class="avatar" id="profile-btn"></i>

            <div class="dropdown hidden" id="profile-dropdown">
                <a href="profile.php">My Profile</a>
                <a href="../auth/logout.php">Log Out</a>
            </div>
        </div>
    </div>
</header>
    <section class="content">
      <div class="card-grid"> 
    </div>
        <?php
          // Admin metrics via helper functions
          $totalUsers = getTotalUsers($pdo);
          $adminUsers = getAdminUsersCount($pdo);
          $recentSignups = getRecentSignupsCount($pdo, 30);
          $assignedTrainings = getAssignedTrainingsCount($pdo);
          $totalBadges = getTotalBadgesCount($pdo);
          $avgScore = getAverageScore($pdo);
          $avgScoreDisplay = $avgScore !== null ? round($avgScore, 1) . '%' : 'N/A';
        ?>

        <div class="card-grid">
          <div class="card">
            <h3>Total Users</h3>
            <p><?= htmlspecialchars((string)$totalUsers) ?></p>
          </div>

          <div class="card">
            <h3>Admin Users</h3>
            <p><?= htmlspecialchars((string)$adminUsers) ?></p>
          </div>

          <div class="card">
            <h3>Recent Signups</h3>
            <p><?= htmlspecialchars((string)$recentSignups) ?></p>
          </div>

          <div class="card">
            <h3>Training Modules Assigned to Users</h3>
            <p><?= htmlspecialchars((string)$assignedTrainings) ?></p>
          </div>

          <div class="card">
            <h3>Total Badges Earned By Users</h3>
            <p><?= htmlspecialchars((string)$totalBadges) ?></p>
          </div>

          <div class="card">
            <h3>Average Score</h3>
            <p><?= htmlspecialchars((string)$avgScoreDisplay) ?></p>
          </div>
        </div>
      </section>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="../js/scripts.js"></script>
</body>
</html>