<?php

session_start();

require_once("../config/db.php");
require_once("../functions/functions.php");

if (!isset($_SESSION["user_id"])) {
    header("Location: ../auth/login.php");
    exit();
}

$user = getUserByID($pdo, $_SESSION["user_id"]);
$message = "";
$message_type = "success";

if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $currentPassword = $_POST["current_password"] ?? "";
    $newPassword = $_POST["new_password"] ?? "";
    $confirmPassword = $_POST["confirm_password"] ?? "";

    if (empty($currentPassword) || empty($newPassword) || empty($confirmPassword)) {
        $message = "All password fields are required.";
        $message_type = "error";
    } elseif (!password_verify($currentPassword, $user["password_hash"])) {
        $message = "Current password is incorrect.";
        $message_type = "error";
    } elseif ($newPassword !== $confirmPassword) {
        $message = "New password and confirmation do not match.";
        $message_type = "error";
    } elseif (strlen($newPassword) < 8) {
        $message = "New password must be at least 8 characters long.";
        $message_type = "error";
    } else {
        updateUserPassword($pdo, $_SESSION["user_id"], password_hash($newPassword, PASSWORD_DEFAULT));
        $message = "Password updated successfully.";
        $message_type = "success";
    }

    $user = getUserByID($pdo, $_SESSION["user_id"]);
}
?>

<!DOCTYPE html> 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Dashboard</title>
    <link rel="stylesheet" href="../css/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

</head>
<body>
    <div class="layout">
  <aside class="sidebar">
    <div class="logo">
        <img src="../images/placeholder_logo_1.png" alt="PhishAware Logo"> <!-- Replace with non-placeholder logo. This logo was generated by Gemini for testing. We should probably remove this placeholder before final submission. -->
        <span> | PhishAware</span>
    </div>
    <nav>
      <?php if ($user["role"] === "admin"): ?>
        <a href="admin-dashboard.php"><i class="fas fa-home"></i> | Admin Dashboard</a>
        <a href="training.php"><i class="fas fa-graduation-cap"></i> | Assign Training</a>
        <a href="results.php"><i class="fas fa-chart-line"></i> | User Results</a>
        <a href="user-lookup.php"><i class="fas fa-users"></i> | Users</a>
        <a href="profile.php"><i class="fas fa-user"></i> | My Profile</a>
        <a href="../auth/logout.php"><i class="fas fa-sign-out-alt"></i> | Log Out</a>
      <?php else: ?>
        <a href="user-dashboard.php"><i class="fas fa-home"></i> | My Dashboard</a>
        <a href="training.php"><i class="fas fa-graduation-cap"></i> | Training</a>
        <a href="phishing-emails.php"><i class="fas fa-envelope"></i> | Phishing Simulation</a>
        <a href="results.php"><i class="fas fa-chart-line"></i> | Results</a>
        <a href="badges.php"><i class="fas fa-trophy"></i> | Badges</a>
        <a href="profile.php"><i class="fas fa-user"></i> | My Profile</a>
        <a href="../auth/logout.php"><i class="fas fa-sign-out-alt"></i> | Log Out</a>
      <?php endif; ?>
    </nav>
  </aside>
  <div class="main">
    <header class="topbar">
      <div class="topbar-left">
        <span>Welcome, <?= htmlspecialchars($user["first_name"]) ?> <?= htmlspecialchars($user["last_name"]) ?></span>
      </div>
            <div class="topbar-right">
            <button id="notifications-btn"><i class="fas fa-bell"></i></button>
            <div class="profile-menu">
                <i class="fas fa-user" alt="Profile" class="avatar" id="profile-btn"></i>
                    <div class="dropdown hidden" id="profile-dropdown">
                    <a href="profile.php">My Profile</a>
                    <a href="../auth/logout.php">Log Out</a>
                    </div>
                </div>
    </header>
    <section class="content">
      <?php if (!empty($message)): ?>
        <div class="message <?= $message_type === "success" ? "success" : "error" ?>">
            <?= htmlspecialchars($message) ?>
        </div>
      <?php endif; ?>
      <div class="card-grid">
        <div class="card">
            <h3>User Profile</h3>
            <p><strong>First Name:</strong> <?= htmlspecialchars($user["first_name"]) ?></p>
            <p><strong>Last Name:</strong> <?= htmlspecialchars($user["last_name"]) ?></p>
            <p><strong>User Role:</strong> <?= htmlspecialchars($user["role"]) ?></p>
            <p><strong>Email:</strong> <?= htmlspecialchars($user["email"]) ?></p>
            <p><strong>Member Since:</strong> <?= htmlspecialchars(date("F j, Y", strtotime($user["created_at"]))) ?></p>
        </div>
        <div class="card">
            <h3>Reset Password</h3>
            <form method="POST" class="profile-form">
                <label for="current_password" class="form-label">Current Password</label>
                <input type="password" name="current_password" id="current_password" class="form-input" required>

                <label for="new_password" class="form-label">New Password</label>
                <input type="password" name="new_password" id="new_password" class="form-input" required minlength="8">

                <label for="confirm_password" class="form-label">Confirm New Password</label>
                <input type="password" name="confirm_password" id="confirm_password" class="form-input" required minlength="8">

                <button type="submit" class="btn secondary">Save New Password</button>
            </form>
        </div>
      </div>
    </div>
    </section>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="../js/scripts.js"></script>
</body>
</html>