<?php

session_start();

require_once("../config/db.php");
require_once("../functions/functions.php");

if (!isset($_SESSION["user_id"])) {
    header("Location: ../auth/login.php");
    exit();
}

$user = getUserByID($pdo, $_SESSION["user_id"]);
$assignedTraining = getAssignedTrainingCount($pdo, $_SESSION["user_id"]);
$badgeCount = getBadgeCount($pdo, $_SESSION["user_id"]);

?>

<!DOCTYPE html> 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Dashboard</title>
    <link rel="stylesheet" href="../css/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

</head>
<body>
    <div class="layout">
  <aside class="sidebar">
    <div class="logo">
        <img src="../images/placeholder_logo_1.png" alt="PhishAware Logo"> <!-- Replace with non-placeholder logo. This logo was generated by Gemini for testing. We should probably remove this placeholder before final submission. -->
        <span> | PhishAware</span>
    </div>
    <nav> <!-- Navigation links, map all of these to their respective pages -->
      <a href="user-dashboard.php"><i class="fas fa-home"></i> | My Dashboard</a>
      <a href="training.php"><i class="fas fa-graduation-cap"></i> | Training</a>
      <a href="results.php"><i class="fas fa-chart-line"></i> | Results</a>
      <a href="badges.php"><i class="fas fa-trophy"></i> | Badges</a>
    </nav>
  </aside>
  <div class="main">
    <header class="topbar">
      <div class="topbar-left">
        <span>Welcome, <?= htmlspecialchars($user["first_name"]) ?> <?= htmlspecialchars($user["last_name"]) ?></span>
        <div class="search-box">
            <i class="fas fa-search"></i>
            <input type="text" placeholder="Search your training, results, badges...">
        </div>
      </div>
            <div class="topbar-right">
            <button id="notifications-btn"><i class="fas fa-bell"></i></button>
            <div class="profile-menu">
                <img src="../images/default_pfp.jpg" alt="Profile" class="avatar" id="profile-btn">
                    <div class="dropdown hidden" id="profile-dropdown">
                    <a href="profile.php">My Profile</a>
                    <a href="../auth/logout.php">Log Out</a>
                    </div>
                </div>
    </header>
    <section class="content">
      <div class="card-grid"> <!-- All of these cards are for displaying user information and training progress, they are currently placeholders. ADD LOGIC TO POPULATE THEM WITH ACTUAL DATA!!! -->
  <div class="card">
    <h3>Assigned Trainings Completed</h3>
    <p><?= $assignedTraining["count"] ?></p>
  </div>

  <div class="card">
    <h3>Last Training Score</h3>
    <p></p>
  </div>

  <div class="card">
    <h3>Badges Earned</h3>
    <p><?= $badgeCount["count"] ?></p>
  </div>

  <div class="card">
    <h3>Next Assigned Training</h3>
    <p></p>
  </div>

  <div class="card">
    <h3>Not Assigned</h3>
    <p></p>
  </div>

  <div class="card">
    <h3>Not Assigned</h3>
    <p></p>
  </div>

  <div class="card wide-card">
    <h3>Your Training Overview</h3>
    <div class="chart-container">
    <canvas id="overviewChart"></canvas>
    </div>

    
  </div>
    </div>
    </section>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="../js/scripts.js"></script>
</body>
</html>